### ISSUE TITLE
Type stub generation should check syntax is valid

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-build#122]
See https://github.com/robotpy/robotpy-wpimath/issues/7

**Comment by virtuald** [comment]
This is a bug in pybind11-stubgen, file it there.

**Comment by virtuald** [comment]
Ha, I already filed it for you back in September. :) 

https://github.com/sizmailov/pybind11-stubgen/issues/47

... you seem skilled in the art of type checking, you could fix it for them.
