### ISSUE TITLE
Replace toml package usage

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-build#133]
The `toml` package is unfortunately unmaintained, and implements TOML v0.5.0. The rest of the ecosystem has moved to support TOML v1.0.0.

There are a few TOML v1.0.0 libraries we could use, including:

- https://github.com/hukkin/tomli
- https://github.com/sdispater/tomlkit

**Comment by JawadHalabiMTB** [comment]
Hi @auscompgeek  where exactly you use that package ?

**Comment by auscompgeek** [comment]
@JawadHalabiMTB If you search the code for `toml.` you should find all usages of it. It's used in several places.

**Comment by TheTripleV** [comment]
There seems to be a push to get tomli included in stdlib. https://github.com/hukkin/tomli/issues/141

**Comment by virtuald** [comment]
tomli seems like a good choice

**Comment by JawadHalabiMTB** [comment]
@auscompgeek 10x man so we can just add tomli package to setup.cfg under [options]->install_requires i guess

**Comment by auscompgeek** [comment]
Well, the code would also have to be updated to use tomli, but yes that'd be the first step.

**Comment by JawadHalabiMTB** [comment]
Sure that's my thought as well i mean for sure it should be installed via pip and then just replace all the "import toml" with "import tomli" as wel as the usage and still don't break functionality Ex: toml.load(). I am on it

**Comment by JawadHalabiMTB** [comment]
Please note that tomli ntends to be minimal so it has no dump/s function which is required by the project so i think we should rethink about the tomli solution
