### ISSUE TITLE
Switch back to schematics from pydantic

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-build#14]
The whole point of using something like schematics is not just massaging data types (which is useful), but it also validates the data and tells the user that they messed up. 

pydantic might get this in the future (https://github.com/samuelcolvin/pydantic/issues/1098) but until it does we just end up with erroneous data which you'll never figure out why it's an error.

**Comment by virtuald** [comment]
The biggest problem is that when I pass a dictionary with keys that aren't in the BaseModel, I want it to tell me that I misspelled one of them. For example, this should fail, and it doesn't.

```
from pydantic import BaseModel
from typing import Optional

class Config(BaseModel):
    key1: Optional[str]

cfg = Config(key2="invalid")
```

**Comment by auscompgeek** [comment]
pydantic already fulfills the use-case of invalid fields: https://pydantic-docs.helpmanual.io/usage/model_config/ (the extra config)
