### ISSUE TITLE
[BUG]: Type hint order matters for VSCode intellisense

### ISSUE THREAD

**Issue by TheTripleV** [robotpy/robotpy-build#162]
### Problem description

Might not be an issue and may be a side-effect of robotpy/robotpy-wpimath#29.

From pathplannerlib's generated `.pyi` file:
```py
class PathPlannerTrajectory():
    class PathPlannerState():
        ... # stuff here
    class Waypoint():
        ... # stuff here
    def asWPILibTrajectory(self) -> wpimath._controls._controls.trajectory.Trajectory: ...
    def getEndState(self) -> PathPlannerTrajectory.PathPlannerState: ...
    def getInitialState(self) -> PathPlannerTrajectory.PathPlannerState: ...
    def getState(self, i: int) -> PathPlannerTrajectory.PathPlannerState: ...
    def getStates(self) -> typing.List[PathPlannerTrajectory.PathPlannerState]: ...
    def getTotalTime(self) -> seconds: ...
    def numStates(self) -> int: ...
    def sample(self, time: seconds) -> PathPlannerTrajectory.PathPlannerState: ...
    pass
```

`PathPlannerTrajectory`'s methods come after internal classes. These methods are not recommended by VSCode and are considered errors by PyRight/PyLance.

### Operating System

MacOS

**Comment by auscompgeek** [comment]
:thinking: I think this is a bug in Pyright. Everything in a type stub should be read as though `from __future__ import annotations` is active, so those return types should be completely valid.

**Comment by virtuald** [comment]
It seems likely that the messed up units are interfering with this. Revisit after those are fixed?

**Comment by TheTripleV** [comment]
It's fine now that the units resolve.
