### ISSUE TITLE
Provide mechanism to disable conversion to None

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-build#200]
Reference: https://github.com/robotpy/robotpy-commands-v2/issues/23

I do wonder if we should disable conversions to None by default for certain types -- in particular std::function. It wouldn't work in every case, but most of the time a passed in std::function is expected to be valid.

**Comment by auscompgeek** [comment]
I presume you mean conversion _from_ None?

**Comment by virtuald** [comment]
words are hard
