### ISSUE TITLE
Fix potential circular dependencies

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-build#43]
I believe the way to fix this is make each class wrapper a class, where the declarations are initialized in the constructor (called in toposort order), and then methods are called 

```
class XWrapper {
  py::class<X> cls_X;

  XWrapper(py::module &m) : cls_X(m, "X") {}

  init_methods() {
     cls_X.def( ) ... 
  }
}
```

For now, I'm going to provide a manual way to override the ordering.

**Comment by virtuald** [comment]
@auscompgeek I wonder if this would fix the documentation issues we were having with names not being registered properly?

**Comment by auscompgeek** [comment]
Sounds like that'd work, yeah. I struggled to figure out a way to create the classes before all the methods before; didn't think of newtypes.
