### ISSUE TITLE
Detect missing Visual Studio runtime issues

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-build#44]
Users get a 'module not found' error, but the module is actually there. Need to provide a better error message.

**Comment by TheTripleV** [comment]
Visual Studio 2019 is build version 27820 or greater.
`reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64`
and
`reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x86`

check for 64 and 32 bit versions of Visual Studio runtimes, respectively.
If the key doesn't exist, then 32 or 64 bit runtime doesn't exist.

`Version` is `v14.24.28127.04` on my machine. Let's call it `vA.B.C.D`. If `C < 27820`, then the runtime found is pre-2019.

`winreg` (builtin) or `python-registry` (pypi but easier?) can be used for this.

**Comment by TheTripleV** [comment]
`reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64` also works but `reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x86` doesn't (they don't have `Wow6432Node`). So there is a little discrepancy between 32 bit and 64 bit windows it seems but at most we would be checking 4 registry keys.

**Comment by virtuald** [comment]
I think the most general way we can solve this in robotpy-build is as follows:

* Catch the FileNotFound error around loadlibrary
* Check to see if the file does in fact exist
* If the file exists, tell the user that a dependency of the library is missing, but we don't know what it is
  * On *nix, could try using ldd if available?
  * On Windows, mention that the Visual Studio redist is often needed? Would be nice to get the exact name that was missing
