### ISSUE TITLE
ccache instructions for macos

### ISSUE THREAD

**Issue by TheTripleV** [robotpy/robotpy-build#52]
```
export CC="ccache gcc"
```
is recommended in the docs.

This fails to build the `.so` file on macos.

```
export CC="ccache clang"
export CXX="ccache clang++"
```
works. I suppose gcc and g++ instead of clang would work but I haven't tried it.

**Comment by virtuald** [comment]
Yeah, I ran into this too. I used gcc/g++ instead of clang/clang++.
