### ISSUE TITLE
Enums are not detected by IDE (Vscode)

### ISSUE THREAD

**Issue by TheTripleV** [robotpy/robotpy-build#55]
Environment: Python 3.8.x in Vscode with the python and Intellicode extensions.

The IDE does not provide enums as suggestions to users.

Example:
```python
wpilib.BuiltInAccelerometer.
# OR
wpilib.BuiltInAccelerometer().
```

At this point, methods such as `setRange` appear in the menu but `Range` does not.

Another user faced this issue in https://github.com/pybind/pybind11/issues/1504.

Potential Solutions mentioned in the above issue:

- Use `py::class_` instead of `py::enum_`
- Generate .pyi files

Related to #1

**Comment by TheTripleV** [comment]
I ran into this while migrating my team's 2019 code to 2020. I ended up looking up the names in the wpilibc source but calling `dir(wpilib.BuiltInAccelerometer.Range)` also brings up names. However, this isn't ideal for students to do.

**Comment by TheTripleV** [comment]
Adding `.export_values()` does work.

Ex.
```c++
py::enum_<frc::Accelerometer::Range>(cls_Accelerometer, "Range")
    .value("kRange_2G", frc::Accelerometer::Range::kRange_2G)
    .value("kRange_4G", frc::Accelerometer::Range::kRange_4G)
    .value("kRange_8G", frc::Accelerometer::Range::kRange_8G)
    .value("kRange_16G", frc::Accelerometer::Range::kRange_16G)
    .export_values()
;
```

However, the enum values are not populated under `wpilib.BuiltInAccelerometer.Range.kRange_xG`. Rather they are under `wpilib.BuiltInAccelerometer.kRange_xG`

**Comment by auscompgeek** [comment]
Out of curiosity, does wpilib.AnalogTriggerType show up?

**Comment by auscompgeek** [comment]
Interestingly, mypy's stubgen also struggles with enums within classes, but is fine with an enum at the top level.

**Comment by TheTripleV** [comment]
AnalogTriggerType does show up.
wpilib.interfaces.Accelerometer.Range doesn't.

**Comment by virtuald** [comment]
I don't want to use export_values(), that seems bad. I think the real answer here is to actually fix/generate our documentation, and create pyi files?

**Comment by TheTripleV** [comment]
Enums created appear to include their values infinitely:
```
>>> wpilib.BuiltInAccelerometer.Range.kRange_2G.kRange_4G.kRange_2G == wpilib.BuiltInAccelerometer.Range.kRange_2G
True

>>> wpilib.BuiltInAccelerometer.Range.kRange_2G.kRange_2G.kRange_2G.kRange_2G.kRange_2G == wpilib.BuiltInAccelerometer.Range.kRange_2G
True
```

**Comment by auscompgeek** [comment]
For me in VS Code, with Microsoft's Python extension, `Range` does appear as a `wpilib.BuiltInAccelerometer` member, but no members are suggested for `wpilib.BuiltInAccelerometer.Range`.

**Comment by auscompgeek** [comment]
Since we now generate type stubs, I believe this is no longer an issue.
