### ISSUE TITLE
Functions that take enums as parameters do not accept ints

### ISSUE THREAD

**Issue by TheTripleV** [robotpy/robotpy-build#68]
Example:
```python
accelerometer_obj.setRange( accelerometer_obj.Range.kRange_2G )
```
and
```python
accelerometer_obj.setRange( accelerometer_obj.Range(0) )
```
work.

But,
```python
accelerometer_obj.setRange( 0 )
```
does not as it did in 2019.

Potential Solutions:

1. Overload these functions with type `int` and static cast them to the enum type. This will cast any int to enum. If a user specifies a bad number, we would need to add in a check (or hope the code crashes somewhere else).

**Comment by auscompgeek** [comment]
I'm inclined to call this intentional (thank goodness pybind11 enums are actually type-safe). See https://github.com/robotpy/robotpy-wpilib/issues/78#issuecomment-352151012

**Comment by virtuald** [comment]
I agree. However, if there are enums that are intended to be bitfields, then we should mark those as `py::arithmetic`. I don't recall if robotpy-build supports that yet.
